  # File: jobs/build.yml

parameters:
  name: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  strategy:
    maxParallel: 3
    matrix:
      node-22:
        node_version: ^22.11.0
      node-20:
        node_version: ^20.9.0
      node-18:
        node_version: ^18.12.0
  steps:
  - task: NodeTool@0
    displayName: " Install Node.js"
    inputs:
      versionSpec: $(node_version)
  - script: git config --global user.email "example@example.com"
  - script: git config --global user.name "Example Git User"
  - script: npm install -g pnpm@9
    displayName: "Setup pnpm"
  - script: npm install
  - script: npm run build
  - script: npm test && npm run write-coverage
  - script: bash logo/generate.sh
    condition: eq(variables['Agent.OS'], 'Linux')
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: '**/junit-*.xml'
      testRunTitle: TestRun ${{ parameters.name }} $(node_version)
  - task: PublishCodeCoverageResults@1
    displayName: 'Publish code coverage results'
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: '**/coverage/cobertura-coverage.xml'
  - task: PublishBuildArtifacts@1
    displayName: Publish packages
    condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
