  # File: jobs/build.yml

parameters:
  name: ''
  pool: ''
  sign: false

jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  strategy:
    maxParallel: 4
    matrix:
      node-26:
        node_version: ^26.8.1
      node-24:
        node_version: ^24.20.0
      node-22:
        node_version: ^22.23.2
      node-20:
        node_version: ^20.20.2
  steps:
  - task: UseNode@1
    displayName: "Install Node.js"
    inputs:
      version: $(node_version)
  - script: git config --global user.email "example@example.com"
  - script: git config --global user.name "Example Git User"
  - script: npm install -g pnpm@12
    displayName: "Setup pnpm"
  - script: npm install
  - script: npm run build
  - script: npm test && npm run write-coverage
  - script: bash logo/generate.sh
    condition: eq(variables['Agent.OS'], 'Linux')
  - task: PublishTestResults@2
    displayName: 'Publish Test Results'
    inputs:
      testResultsFiles: 'junit-testresults.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      testRunTitle: TestRun ${{ parameters.name }} $(node_version)
  - task: PublishCodeCoverageResults@2
    displayName: 'Publish code coverage results'
    inputs:
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
  - task: PublishBuildArtifacts@1
    displayName: Publish packages
    condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
